{"metadata":{"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.12.8"}},"nbformat_minor":5,"nbformat":4,"cells":[{"id":"c39b76fb-259f-4e16-a44d-02a295c82386","cell_type":"markdown","source":"# Simple Workflow with pyiron_base","metadata":{}},{"id":"3638419b-a0cb-49e2-b157-7fbb1acde90f","cell_type":"markdown","source":"## Define workflow with pyiron_base","metadata":{}},{"id":"b4a78447-e87c-4fb4-8d17-d9a280eb7254","cell_type":"code","source":"from pyiron_base import Project, job","metadata":{"trusted":true},"outputs":[],"execution_count":1},{"id":"06c2bd9e-b2ac-4b88-9158-fa37331c3418","cell_type":"code","source":"from python_workflow_definition.pyiron_base import write_workflow_json","metadata":{"trusted":true},"outputs":[],"execution_count":2},{"id":"fb847d49-7bf9-4839-9b99-c116d1b0e9ee","cell_type":"code","source":"from simple_workflow import (\n    add_x_and_y as _add_x_and_y, \n    add_x_and_y_and_z as _add_x_and_y_and_z,\n)","metadata":{"trusted":true},"outputs":[],"execution_count":3},{"id":"8f95244e","cell_type":"code","source":"workflow_json_filename = \"pyiron_base_simple.json\"","metadata":{"trusted":true},"outputs":[],"execution_count":4},{"id":"07598344-0f75-433b-8902-bea21a42088c","cell_type":"code","source":"add_x_and_y = job(_add_x_and_y, output_key_lst=[\"x\", \"y\", \"z\"])\nadd_x_and_y_and_z = job(_add_x_and_y_and_z)","metadata":{"trusted":true},"outputs":[],"execution_count":5},{"id":"ecef1ed5-a8d3-48c3-9e01-4a40e55c1153","cell_type":"code","source":"pr = Project(\"test\")\npr.remove_jobs(recursive=True, silently=True)","metadata":{"trusted":true},"outputs":[{"output_type":"display_data","data":{"text/plain":"0it [00:00, ?it/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"37f4bde844fc45fc8854dfcdc20cd5cc"}},"metadata":{}}],"execution_count":6},{"id":"2b88a30a-e26b-4802-89b7-79ca08cc0af9","cell_type":"code","source":"obj = add_x_and_y(x=1, y=2, pyiron_project=pr)","metadata":{"trusted":true},"outputs":[],"execution_count":7},{"id":"a5e5ca63-2906-47c9-bac6-adebf8643cba","cell_type":"code","source":"w = add_x_and_y_and_z(x=obj.output.x, y=obj.output.y, z=obj.output.z, pyiron_project=pr)","metadata":{"trusted":true},"outputs":[],"execution_count":8},{"id":"e464da97-16a1-4772-9a07-0a47f152781d","cell_type":"code","source":"write_workflow_json(delayed_object=w, file_name=workflow_json_filename)","metadata":{"trusted":true},"outputs":[],"execution_count":9},{"id":"bca646b2-0a9a-4271-966a-e5903a8c9031","cell_type":"code","source":"!cat {workflow_json_filename}","metadata":{"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":"{\"nodes\": {\"0\": \"simple_workflow.add_x_and_y_and_z\", \"1\": \"simple_workflow.add_x_and_y\", \"2\": 1, \"3\": 2}, \"edges\": [{\"target\": 0, \"targetHandle\": \"x\", \"source\": 1, \"sourceHandle\": \"x\"}, {\"target\": 1, \"targetHandle\": \"x\", \"source\": 2, \"sourceHandle\": null}, {\"target\": 1, \"targetHandle\": \"y\", \"source\": 3, \"sourceHandle\": null}, {\"target\": 0, \"targetHandle\": \"y\", \"source\": 1, \"sourceHandle\": \"y\"}, {\"target\": 0, \"targetHandle\": \"z\", \"source\": 1, \"sourceHandle\": \"z\"}]}"}],"execution_count":10},{"id":"a4c0faaf-e30d-4ded-8e9f-57f97f51b14c","cell_type":"markdown","source":"## Load Workflow with aiida","metadata":{}},{"id":"2ecc229f-daa1-49b9-9279-a6b5ae1aa4f2","cell_type":"code","source":"from aiida import load_profile\n\nload_profile()","metadata":{"trusted":true},"outputs":[{"execution_count":11,"output_type":"execute_result","data":{"text/plain":"Profile<uuid='0911f03384b24f139c7cf96149242165' name='adis'>"},"metadata":{}}],"execution_count":11},{"id":"68a56b32-9f99-43d7-aaee-0c1cd9522681","cell_type":"code","source":"from python_workflow_definition.aiida import load_workflow_json","metadata":{"trusted":true},"outputs":[],"execution_count":12},{"id":"8f2a621d-b533-4ddd-8bcd-c22db2f922ec","cell_type":"code","source":"wg = load_workflow_json(file_name=workflow_json_filename)\nwg","metadata":{"trusted":true},"outputs":[{"execution_count":13,"output_type":"execute_result","data":{"text/plain":"NodeGraphWidget(settings={'minimap': True}, style={'width': '90%', 'height': '600px'}, value={'name': 'WorkGraâ€¦","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":1,"model_id":"09020dadcc3b484883ca641d466aed90"}},"metadata":{}}],"execution_count":13},{"id":"cf80267d-c2b0-4236-bf1d-a57596985fc1","cell_type":"code","source":"\nwg.run()","metadata":{"trusted":true},"outputs":[{"name":"stderr","output_type":"stream","text":"03/22/2025 08:38:57 AM <1011> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [172|WorkGraphEngine|continue_workgraph]: Continue workgraph.\n03/22/2025 08:38:57 AM <1011> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [172|WorkGraphEngine|continue_workgraph]: tasks ready to run: pickle_node3,pickle_node4\n03/22/2025 08:38:57 AM <1011> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [172|WorkGraphEngine|run_tasks]: Run task: pickle_node3, type: PYTHONJOB\n"},{"name":"stdout","output_type":"stream","text":"------------------------------------------------------------\nkwargs:  {'value': 1}\n"},{"name":"stderr","output_type":"stream","text":"03/22/2025 08:38:58 AM <1011> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [172|WorkGraphEngine|run_tasks]: Run task: pickle_node4, type: PYTHONJOB\n"},{"name":"stdout","output_type":"stream","text":"------------------------------------------------------------\nkwargs:  {'value': 2}\n"},{"name":"stderr","output_type":"stream","text":"03/22/2025 08:38:59 AM <1011> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [172|WorkGraphEngine|on_wait]: Process status: Waiting for child processes: 180, 188\n03/22/2025 08:39:01 AM <1011> aiida.scheduler.direct: [WARNING] Unrecognized job_state 'p' for job id Activating\n03/22/2025 08:39:01 AM <1011> aiida.engine.transports: [ERROR] Exception whilst using transport:\nTraceback (most recent call last):\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n    yield transport_request.future\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n    scheduler_response = scheduler.get_jobs(**kwargs)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 269, in get_jobs\n    job_stats = super().get_jobs(jobs=jobs, user=user, as_dict=as_dict)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n    joblist = self._parse_joblist_output(retval, stdout, stderr)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 253, in _parse_joblist_output\n    this_job.wallclock_time_seconds = self._convert_time(job[3])\n                                                         ~~~^^^\nIndexError: list index out of range\n\nTask exception was never retrieved\nfuture: <Task finished name='Task-10' coro=<JobsList._ensure_updating.<locals>.updating() done, defined at /srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py:179> exception=IndexError('list index out of range')>\nTraceback (most recent call last):\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/tasks.py\", line 314, in __step_run_and_handle_result\n    result = coro.send(None)\n             ^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 181, in updating\n    await self._update_job_info()\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n    self._jobs_cache = await self._get_jobs_from_scheduler()\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n    scheduler_response = scheduler.get_jobs(**kwargs)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 269, in get_jobs\n    job_stats = super().get_jobs(jobs=jobs, user=user, as_dict=as_dict)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n    joblist = self._parse_joblist_output(retval, stdout, stderr)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 253, in _parse_joblist_output\n    this_job.wallclock_time_seconds = self._convert_time(job[3])\n                                                         ~~~^^^\nIndexError: list index out of range\n03/22/2025 08:39:01 AM <1011> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 1 of do_update excepted, retrying after 20 seconds\nTraceback (most recent call last):\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n    result = await coro()\n             ^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 195, in do_update\n    job_info = await cancellable.with_interrupt(update_request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n    result = await next(wait_iter)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/tasks.py\", line 631, in _wait_for_one\n    return f.result()  # May raise f.exception().\n           ^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/futures.py\", line 202, in result\n    raise self._exception.with_traceback(self._exception_tb)\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n    self._jobs_cache = await self._get_jobs_from_scheduler()\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n    scheduler_response = scheduler.get_jobs(**kwargs)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 269, in get_jobs\n    job_stats = super().get_jobs(jobs=jobs, user=user, as_dict=as_dict)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n    joblist = self._parse_joblist_output(retval, stdout, stderr)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 253, in _parse_joblist_output\n    this_job.wallclock_time_seconds = self._convert_time(job[3])\n                                                         ~~~^^^\nIndexError: list index out of range\n03/22/2025 08:39:01 AM <1011> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 1 of do_update excepted, retrying after 20 seconds\nTraceback (most recent call last):\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n    result = await coro()\n             ^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 195, in do_update\n    job_info = await cancellable.with_interrupt(update_request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n    result = await next(wait_iter)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/tasks.py\", line 631, in _wait_for_one\n    return f.result()  # May raise f.exception().\n           ^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/futures.py\", line 202, in result\n    raise self._exception.with_traceback(self._exception_tb)\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n    self._jobs_cache = await self._get_jobs_from_scheduler()\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n    scheduler_response = scheduler.get_jobs(**kwargs)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 269, in get_jobs\n    job_stats = super().get_jobs(jobs=jobs, user=user, as_dict=as_dict)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n    joblist = self._parse_joblist_output(retval, stdout, stderr)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 253, in _parse_joblist_output\n    this_job.wallclock_time_seconds = self._convert_time(job[3])\n                                                         ~~~^^^\nIndexError: list index out of range\n03/22/2025 08:39:21 AM <1011> aiida.scheduler.direct: [WARNING] Unrecognized job_state 'p' for job id Activating\n03/22/2025 08:39:21 AM <1011> aiida.engine.transports: [ERROR] Exception whilst using transport:\nTraceback (most recent call last):\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n    yield transport_request.future\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n    scheduler_response = scheduler.get_jobs(**kwargs)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 269, in get_jobs\n    job_stats = super().get_jobs(jobs=jobs, user=user, as_dict=as_dict)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n    joblist = self._parse_joblist_output(retval, stdout, stderr)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 253, in _parse_joblist_output\n    this_job.wallclock_time_seconds = self._convert_time(job[3])\n                                                         ~~~^^^\nIndexError: list index out of range\n\nTask exception was never retrieved\nfuture: <Task finished name='Task-11' coro=<JobsList._ensure_updating.<locals>.updating() done, defined at /srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py:179> exception=IndexError('list index out of range')>\nTraceback (most recent call last):\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/tasks.py\", line 314, in __step_run_and_handle_result\n    result = coro.send(None)\n             ^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 181, in updating\n    await self._update_job_info()\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n    self._jobs_cache = await self._get_jobs_from_scheduler()\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n    scheduler_response = scheduler.get_jobs(**kwargs)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 269, in get_jobs\n    job_stats = super().get_jobs(jobs=jobs, user=user, as_dict=as_dict)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n    joblist = self._parse_joblist_output(retval, stdout, stderr)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 253, in _parse_joblist_output\n    this_job.wallclock_time_seconds = self._convert_time(job[3])\n                                                         ~~~^^^\nIndexError: list index out of range\n03/22/2025 08:39:21 AM <1011> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 2 of do_update excepted, retrying after 40 seconds\nTraceback (most recent call last):\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n    result = await coro()\n             ^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 195, in do_update\n    job_info = await cancellable.with_interrupt(update_request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n    result = await next(wait_iter)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/tasks.py\", line 631, in _wait_for_one\n    return f.result()  # May raise f.exception().\n           ^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/futures.py\", line 202, in result\n    raise self._exception.with_traceback(self._exception_tb)\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n    self._jobs_cache = await self._get_jobs_from_scheduler()\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n    scheduler_response = scheduler.get_jobs(**kwargs)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 269, in get_jobs\n    job_stats = super().get_jobs(jobs=jobs, user=user, as_dict=as_dict)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n    joblist = self._parse_joblist_output(retval, stdout, stderr)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 253, in _parse_joblist_output\n    this_job.wallclock_time_seconds = self._convert_time(job[3])\n                                                         ~~~^^^\nIndexError: list index out of range\n03/22/2025 08:39:21 AM <1011> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 2 of do_update excepted, retrying after 40 seconds\nTraceback (most recent call last):\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n    result = await coro()\n             ^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 195, in do_update\n    job_info = await cancellable.with_interrupt(update_request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n    result = await next(wait_iter)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/tasks.py\", line 631, in _wait_for_one\n    return f.result()  # May raise f.exception().\n           ^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/futures.py\", line 202, in result\n    raise self._exception.with_traceback(self._exception_tb)\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n    self._jobs_cache = await self._get_jobs_from_scheduler()\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n    scheduler_response = scheduler.get_jobs(**kwargs)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 269, in get_jobs\n    job_stats = super().get_jobs(jobs=jobs, user=user, as_dict=as_dict)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n    joblist = self._parse_joblist_output(retval, stdout, stderr)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 253, in _parse_joblist_output\n    this_job.wallclock_time_seconds = self._convert_time(job[3])\n                                                         ~~~^^^\nIndexError: list index out of range\n"}],"execution_count":null},{"id":"0c3503e1-0a32-40e1-845d-3fd9ec3c4c19","cell_type":"markdown","source":"## Load Workflow with jobflow","metadata":{}},{"id":"4abb0481-8e38-479d-ae61-6c46d091653e","cell_type":"code","source":"from python_workflow_definition.jobflow import load_workflow_json","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"id":"4b45e83b-945f-48c5-8e20-9df0ce0a14a1","cell_type":"code","source":"flow = load_workflow_json(file_name=workflow_json_filename)","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"id":"8665c39c-220c-4982-b738-c31f6460530f","cell_type":"code","source":"result = run_locally(flow)\nresult","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"id":"cf76f305-24de-45a7-be8e-cfe45cd6458e","cell_type":"code","source":"","metadata":{"trusted":true},"outputs":[],"execution_count":null}]}